services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: serial_watchers
      MARIADB_USER: serial_watchers_user
      MARIADB_PASSWORD: serial_watchers_pwd
    volumes:
      - database_swcarole:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database_swcarole:
